version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: video_sharing_app
    container_name: app
    entrypoint: ./docker-entrypoint.sh
    tty: true
    stdin_open: true
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - bundle:/bundle
    environment:
      RAILS_ENV: development
      RAILS_MASTER_KEY: 5b98d20cb24ff9b81b48961fc3401307 # It should be share internally and set it to config/credentials/development.key
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: 123456a@
      REDIS_URL: redis://redis:6379/1
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: 123456a@
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:6.0.5-alpine
    container_name: redis
    tty: true
    ports:
      - '6380:6379'
volumes:
  bundle:
  db_data:
